import { useEffect, useState } from 'react'
import { DEFAULT_GLOWS } from '../data/defaultGlows'
import { GlowEditor, type GlowMap } from './GlowEditor'
import { PlanetGL } from './PlanetGL'
import { SceneTuner } from './SceneTuner'
import { ShipSprite, loadImage } from './ShipSprite'
import { SpaceBackdrop } from './SpaceBackdrop'
import { DEFAULT_SCENE, type SceneParams } from '../lib/spaceRender'
import { KofiLink } from './KofiLink'

// Two tiers of acknowledgment. Boarding always acks the current browser
// session (sessionStorage), so a refresh doesn't re-gate. "Remember for
// next time" additionally acks permanently (localStorage). v2: the v1
// localStorage ack was set on every entry and doesn't count as opt-in.
const WELCOME_KEY = 'shc-welcome-v2'
const WELCOME_SESSION_KEY = 'shc-welcome-session'
const SCENE_KEY = 'shc-scene-v1'
const GLOW_KEY = 'shc-glows-v1'
const GL_PLANET_KEY = 'shc-gl-planet-v1'

function loadGlows(): GlowMap {
  try {
    const raw = localStorage.getItem(GLOW_KEY)
    // the shipped fleet dressing unless this browser has authored its own
    const map = raw ? (JSON.parse(raw) as GlowMap) : structuredClone(DEFAULT_GLOWS)
    // marks authored with the old washed-out swatches pick up the saturated
    // colors without re-authoring
    const RECOLOR: Record<string, string> = {
      '#7de0d0': '#28e2cc',
      '#14e8cf': '#28e2cc',
      '#8dff57': '#66ff21',
      '#ffb454': '#ffa514',
      '#ff9a54': '#ff7a14',
      '#7aa7ff': '#2979ff',
      '#ff6b7a': '#ff3d55',
    }
    for (const marks of Object.values(map)) {
      for (const m of marks) m.color = RECOLOR[m.color] ?? m.color
    }
    return map
  } catch {
    return {}
  }
}

function loadScene(): SceneParams {
  try {
    const raw = localStorage.getItem(SCENE_KEY)
    return raw ? { ...DEFAULT_SCENE, ...JSON.parse(raw) } : { ...DEFAULT_SCENE }
  } catch {
    return { ...DEFAULT_SCENE }
  }
}

function loadGlPlanet(): boolean {
  try {
    // shader planet is the default (dev can opt back to drawn via the toggle)
    return localStorage.getItem(GL_PLANET_KEY) !== '0'
  } catch {
    return true
  }
}

export function welcomeAcknowledged(): boolean {
  try {
    return (
      localStorage.getItem(WELCOME_KEY) === 'ack' ||
      sessionStorage.getItem(WELCOME_SESSION_KEY) === 'ack'
    )
  } catch {
    return true
  }
}

const BASE = import.meta.env.BASE_URL

/** A ship in the scene: sprite, offset (%) from the fleet anchor, width (px),
 * surge timing.
 *
 * Depth is implicit: the wg-drift surge keyframes translate in %s of each
 * ship's own box, so every ship covers the same PHYSICAL distance and the
 * screen amplitude scales with rendered size — which is 1/distance. The
 * parallax is generated by the fleet's own motion, not the viewer's. */
interface ShipSpec {
  src: string
  dx: number
  dy: number
  width: number
  drift: number // seconds per surge half-cycle
  delay: number // phase offset — applied negative so ships start mid-path
  /** mirror horizontally */
  flip?: boolean
}

// formation matched to the game's main-menu key art: the flagship vast and
// nearest, spanning the frame center-left; a freighter running high above;
// strays scattered off the port side; two escorts trailing low; a distant
// pair silhouetted against the planet's limb. All offsets from the fleet
// anchor so fleetX/fleetY still moves the whole scene.
// the key-art arrangement, shifted a third of the frame right so the fleet
// clears the logo and warning copy on the left
const SHIPS: ShipSpec[] = [
  // freighter running beneath the flagship's keel
  { src: 'ship-hf1', dx: -17, dy: 8, width: 160, drift: 13, delay: 3.0, flip: true },
  // tiny scout running point, front and centre of the fleet
  { src: 'ship-fs3', dx: 12, dy: 22, width: 46, drift: 11, delay: 0.5 },
  // small stray off the port beam
  { src: 'ship-fs2', dx: -21, dy: 19, width: 56, drift: 13, delay: 2.1 },
  // escort below the flagship's engines, on the dark face
  { src: 'ship-hf2', dx: -5, dy: 23, width: 90, drift: 12, delay: 4.2, flip: true },
  // chunky escort, bottom left of the group
  { src: 'ship-hf1', dx: -14, dy: 30, width: 140, drift: 14, delay: 5.5, flip: true },
  // trailing escort, bottom middle
  { src: 'ship-hf2', dx: 14, dy: 35, width: 120, drift: 12, delay: 1.6, flip: true },
  // distant pair, small against the far side
  { src: 'ship-fs3', dx: 24, dy: 18, width: 44, drift: 10, delay: 2.8 },
  { src: 'ship-fs2', dx: 28, dy: 24, width: 40, drift: 11, delay: 4.9 },
  // the flagship — vast and nearest, crossing in front of the planet
  { src: 'ship-colony', dx: -17, dy: -14, width: 900, drift: 16, delay: 0 },
]

// Warp-in cadence, in seconds, added on top of the shared title-lead delay.
// Deliberately NOT evenly spaced — an even stagger reads as a flat tick-tick-
// tick. This is a rhythm: two spaced hits, two quick "ticka" bursts, a little
// double-tap, then the flagship (last spec) lands alone on the emphatic beat.
//   tah · · tah · · ti-cka · ti-cka · ti-ti · · · TAH
const WARP_RHYTHM = [0, 0.16, 0.34, 0.4, 0.52, 0.58, 0.7, 0.76, 0.94]

/**
 * First-visit spoiler gate, built from the game's own assets: the main-menu
 * skybox, the official logo, and the background-fleet sprites, the fleet
 * station-keeping with a slow isometric surge. The ledger strips the
 * economy of its mystery — new players deserve one chance to keep it.
 */
export function WelcomeGate({ onEnter }: { onEnter: () => void }) {
  const [exiting, setExiting] = useState(false)
  const [remember, setRemember] = useState(false)
  const [scene, setScene] = useState<SceneParams>(loadScene)
  const [glows, setGlows] = useState<GlowMap>(loadGlows)
  // which planet renderer is live — hand-drawn canvas (default) or the GPU
  // shader planet with live drifting clouds. Toggled from the scene tuner.
  const [glPlanet, setGlPlanet] = useState(loadGlPlanet)
  // load gate: hold the scene hidden until sprites are decoded and the backdrop
  // (+ shader planet, when it's the live renderer) have painted their first
  // frame — then reveal it all as one clean piece instead of a piecemeal pop-in.
  const [imagesReady, setImagesReady] = useState(false)
  const [backdropReady, setBackdropReady] = useState(false)
  const [planetReady, setPlanetReady] = useState(false)
  const [forceReady, setForceReady] = useState(false)
  const showShader = !import.meta.env.DEV || glPlanet
  const ready = forceReady || (imagesReady && backdropReady && (!showShader || planetReady))

  useEffect(() => {
    localStorage.setItem(SCENE_KEY, JSON.stringify(scene))
  }, [scene])
  useEffect(() => {
    localStorage.setItem(GLOW_KEY, JSON.stringify(glows))
  }, [glows])
  useEffect(() => {
    localStorage.setItem(GL_PLANET_KEY, glPlanet ? '1' : '0')
  }, [glPlanet])

  // preload every ship sprite + the logo up front (warms ShipSprite's shared
  // cache, so they render instantly on mount rather than popping in one by one)
  useEffect(() => {
    let live = true
    const urls = [...SHIPS.map((s) => `${BASE}scene/${s.src}.png`), `${BASE}scene/logo.png`]
    void Promise.all(urls.map((u) => loadImage(u).catch(() => null))).then(() => {
      if (live) setImagesReady(true)
    })
    return () => {
      live = false
    }
  }, [])
  // safety net: never leave the scene stuck hidden if a first-frame signal never fires
  useEffect(() => {
    const t = window.setTimeout(() => setForceReady(true), 4000)
    return () => clearTimeout(t)
  }, [])

  // the shimmer ticker: engine flicker and boost breathing at ~12Hz from a
  // single loop. Ambient FX don't need 60fps — and a second concurrent CSS
  // animation family alongside the drift forces Chromium off the compositor
  // fast path into main-thread frames, which is what spins laptop fans.
  useEffect(() => {
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return
    // setInterval, NOT a requestAnimationFrame loop: an rAF loop forces the
    // browser to produce a full frame every vsync even when the callback
    // does nothing — the frames themselves were the CPU cost. This way the
    // page only renders ~12 frames/s for the shimmer.
    const tick = () => {
      const t = performance.now() / 1000
      const cores = document.querySelectorAll<HTMLElement>('.wg-glow-core')
      for (let i = 0; i < cores.length; i++) {
        // uneven two-sine flicker, phase-scattered per element
        const s = i * 2.399
        const v = 0.86 + 0.13 * Math.sin(t * 3.7 + s) * Math.sin(t * 7.3 + s * 1.7)
        cores[i].style.opacity = v.toFixed(3)
      }
      const boosts = document.querySelectorAll<HTMLElement>('.wg-ship-boost')
      for (let i = 0; i < boosts.length; i++) {
        // slow independent breathe per boost
        const s = i * 1.618
        const v = 0.7 + 0.3 * Math.sin(t * (0.9 + (i % 5) * 0.13) + s)
        boosts[i].style.opacity = v.toFixed(3)
      }
    }
    const timer = setInterval(tick, 84)
    return () => clearInterval(timer)
  }, [])

  // No mouse parallax — the viewer isn't actually moving, so head-tracked
  // shift reads as fake. Depth comes from the ships' own station-keeping
  // surge instead: every ship travels the same physical distance along the
  // isometric heading, so screen amplitude falls out of rendered size
  // (wg-drift keyframes use translate %s of the ship's own box).

  const accept = () => {
    // boarding covers the rest of this browser session; the permanent ack
    // is only written when the visitor opts into being remembered
    try {
      sessionStorage.setItem(WELCOME_SESSION_KEY, 'ack')
      if (remember) localStorage.setItem(WELCOME_KEY, 'ack')
    } catch {
      // storage unavailable: the gate will simply ask again next load
    }
    setExiting(true)
    // fire immediately: the app mounts beneath and the exit fade reveals it
    onEnter()
  }

  return (
    <div
      className={`welcome-gate${ready ? ' wg-ready' : ''}${exiting ? ' exiting' : ''}`}
      role="dialog"
      aria-label="Spoiler warning"
    >
      {/* the planet + systems live in a materialise wrapper: on `wg-ready` they
          scale up from a hair under 1.0 and fade in, so the world *arrives*.
          (Canvas sizing uses clientWidth, immune to this transform's scale.) */}
      <div className="wg-materialize">
        <SpaceBackdrop params={scene} onReady={() => setBackdropReady(true)} />
        {/* the GPU shader planet overlays the canvas one at the same placement.
            Production always uses it (the drawn↔shader toggle is dev-only); it
            self-checks for WebGL2 and no-ops (leaving the canvas planet showing)
            where it isn't available. */}
        {showShader && <PlanetGL params={scene} onReady={() => setPlanetReady(true)} />}
      </div>
      {/* Scene tuner ships to everyone — visitors can play with the world.
          The glow author is a local-only dev tool: gated to `vite dev`, it is
          dead-code-eliminated from production builds. */}
      <SceneTuner params={scene} onChange={setScene} glPlanet={glPlanet} onGlPlanetChange={setGlPlanet} />
      {import.meta.env.DEV && <GlowEditor glows={glows} onChange={setGlows} />}
      {SHIPS.map((s, i) => {
        const left = scene.fleetX * 100 + s.dx
        const top = scene.fleetY * 100 + s.dy
        // unit vector from the ship toward the sun, in rough screen space
        // (viewport is wider than tall; weight x accordingly)
        const dx = (scene.sunX * 100 - left) * 1.7
        const dy = scene.sunY * 100 - top
        const len = Math.hypot(dx, dy) || 1
        return (
          <div key={`${s.src}-${i}`} className="wg-layer">
            <ShipSprite
              src={`${BASE}scene/${s.src}.png`}
              width={s.width}
              flip={s.flip}
              drift={s.drift}
              delay={s.delay}
              left={left}
              top={top}
              sunDx={dx / len}
              sunDy={dy / len}
              glows={glows[s.src] ?? []}
              warpDelay={WARP_RHYTHM[i] ?? i * 0.1}
            />
          </div>
        )
      })}
      <div className="welcome-content">
        <img className="welcome-logo" src={`${BASE}scene/logo.png`} alt="Space Haven" draggable={false} />
        <div className="welcome-sub">Production Ledger</div>
        <p className="welcome-warning">
          <strong>Read this before you continue.</strong> This tool lays the game's economy bare. Exact
          recipes, true trade values, and the margin on every item you will fabricate. These are
          learnings the game wants you to discover for yourself, somewhere out in the blackness.
        </p>
        <p className="welcome-warning welcome-soft">
          If you are new to the game, please consider holding off until the initial wonder has abated.
          This tool will be here when you are ready.
        </p>
        <div className="welcome-actions">
          <button className="welcome-enter" onClick={accept}>
            I know what I'm doing, board
          </button>
          <label className="welcome-remember">
            <input
              type="checkbox"
              checked={remember}
              onChange={(ev) => setRemember(ev.target.checked)}
            />
            <span className="welcome-remember-lamp" aria-hidden />
            <span className="welcome-remember-text">Remember for next time</span>
          </label>
        </div>
        <p className="welcome-legal">
          This is an unofficial fan project, not affiliated with or endorsed by Bugbyte Ltd. Space Haven
          and all artwork and game assets shown here are the property of Bugbyte Ltd. This site is free
          and exists to enhance the enjoyment of the game. Enjoying the tool?
          <KofiLink tip="Buy me a coffee" className="kofi-inline" />
        </p>
      </div>
    </div>
  )
}
